# Generated by Django 4.2.4 on 2023-08-26 07:51

from django.db import migrations
from django.db.migrations import RunPython

task_type_info_list = [
    {
        "name": "Task",
    },
    {
        "name": "Sub task",
    },
    {
        "name": "Epic",
    },
]


def create_basic_task_types(apps, schema_editor):
    TaskType = apps.get_model("shark_task_core", "TaskType")
    for task_type_info in task_type_info_list:
        TaskType.objects.create(name=task_type_info["name"])


link_type_info_list = [
    {
        "src_name": "subtask of",
        "dest_name": "task of",
    },
    {
        "src_name": "related to",
        "dest_name": "related to",
    },
]


def create_basic_link_types(apps, schema_editor):
    LinkType = apps.get_model("shark_task_core", "LinkType")
    for link_type_info in link_type_info_list:
        LinkType.objects.create(src_name=link_type_info["src_name"], dest_name=link_type_info["dest_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("shark_task_core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_basic_task_types,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_link_types,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
    ]
