# Generated by Django 4.2.4 on 2023-08-26 07:51

from django.db import migrations
from django.db.migrations import RunPython

select_config_schema = {
    "type": "object",
    "required": ["options"],
    "properties": {
        "options": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id", "name"],
                "properties": {"id": {"type": "integer"}, "name": {"type": "string"}},
            },
        }
    },
}

integer_value_schema = {"type": "object", "required": ["value"], "properties": {"value": {"type": "integer"}}}

string_value_schema = {"type": "object", "required": ["value"], "properties": {"value": {"type": "string"}}}

select_value_schema = {"type": "object", "required": ["value"], "properties": {"value": {"type": "integer"}}}

multi_select_value_schema = {
    "type": "object",
    "required": ["values"],
    "values": {"type": "array", "items": {"type": "integer"}},
}

user_picker_value_schema = {"type": "object", "required": ["value"], "properties": {"value": {"type": "integer"}}}

field_type_info_list = [
    {"key": "integer", "config_schema": None, "value_schema": integer_value_schema},
    {"key": "string", "config_schema": None, "value_schema": string_value_schema},
    {"key": "text", "config_schema": None, "value_schema": string_value_schema},
    {"key": "select", "config_schema": select_config_schema, "value_schema": select_value_schema},
    {"key": "multi_select", "config_schema": select_config_schema, "value_schema": multi_select_value_schema},
    {"key": "user_picker", "config_schema": None, "value_schema": user_picker_value_schema},
]


def create_basic_field_types(apps, schema_editor):
    FieldType = apps.get_model("django_shark_task", "FieldType")
    for field_type_info in field_type_info_list:
        FieldType.objects.create(
            key=field_type_info["key"],
            config_schema=field_type_info["config_schema"],
            value_schema=field_type_info["value_schema"],
        )


field_info_list = [
    {
        "key": "description",
        "name": "Description",
        "field_type_key": "text",
    },
    {
        "key": "reporter",
        "name": "Reporter",
        "field_type_key": "user_picker",
    },
    {
        "key": "assignee",
        "name": "Assignee",
        "field_type_key": "user_picker",
    },
]


def create_basic_fields(apps, schema_editor):
    FieldType = apps.get_model("django_shark_task", "FieldType")
    Field = apps.get_model("django_shark_task", "Field")
    for field_info in field_info_list:
        field_type = FieldType.objects.get(key=field_info["field_type_key"])
        Field.objects.create(key=field_info["key"], name=field_info["name"], field_type=field_type)


status_type_info_list = [
    {
        "name": "ToDo",
    },
    {
        "name": "InProgress",
    },
    {
        "name": "Done",
    },
]


def create_basic_status_types(apps, schema_editor):
    StatusType = apps.get_model("django_shark_task", "StatusType")
    for status_type_info in status_type_info_list:
        StatusType.objects.create(name=status_type_info["name"])


status_info_list = [
    {
        "status_type_name": "ToDo",
        "name": "ToDo",
    },
    {
        "status_type_name": "InProgress",
        "name": "InProgress",
    },
    {
        "status_type_name": "Done",
        "name": "Done",
    },
]


def create_basic_statuses(apps, schema_editor):
    StatusType = apps.get_model("django_shark_task", "StatusType")
    Status = apps.get_model("django_shark_task", "Status")
    for status_info in status_info_list:
        status_type = StatusType.objects.get(name=status_info["status_type_name"])
        Status.objects.create(status_type=status_type, name=status_info["name"])


def create_basic_workflow(apps, schema_editor):
    Status = apps.get_model("django_shark_task", "Status")
    Transition = apps.get_model("django_shark_task", "Transition")
    Workflow = apps.get_model("django_shark_task", "Workflow")

    todo_status = Status.objects.get(name="ToDo")
    in_progress_status = Status.objects.get(name="InProgress")
    done_status = Status.objects.get(name="Done")

    workflow = Workflow.objects.create(name="Basic workflow")
    Transition.objects.create(
        name="Initial", workflow=workflow, src_status=None, dest_status=todo_status, is_initial=True
    )
    Transition.objects.create(
        name="In progress", workflow=workflow, src_status=todo_status, dest_status=in_progress_status, is_initial=False
    )
    Transition.objects.create(
        name="Done", workflow=workflow, src_status=in_progress_status, dest_status=done_status, is_initial=False
    )
    Transition.objects.create(
        name="Stop progress",
        workflow=workflow,
        src_status=in_progress_status,
        dest_status=todo_status,
        is_initial=False,
    )
    Transition.objects.create(
        name="Undone", workflow=workflow, src_status=done_status, dest_status=todo_status, is_initial=False
    )


task_type_info_list = [
    {
        "name": "Task",
    },
    {
        "name": "Sub task",
    },
    {
        "name": "Epic",
    },
]


def create_basic_task_types(apps, schema_editor):
    TaskType = apps.get_model("django_shark_task", "TaskType")
    for task_type_info in task_type_info_list:
        TaskType.objects.create(name=task_type_info["name"])


link_type_info_list = [
    {
        "src_name": "subtask of",
        "dest_name": "task of",
    },
    {
        "src_name": "related to",
        "dest_name": "related to",
    },
]


def create_basic_link_types(apps, schema_editor):
    LinkType = apps.get_model("django_shark_task", "LinkType")
    for link_type_info in link_type_info_list:
        LinkType.objects.create(src_name=link_type_info["src_name"], dest_name=link_type_info["dest_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("django_shark_task", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_basic_field_types,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_fields,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_status_types,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_statuses,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_workflow,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_task_types,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            create_basic_link_types,
            reverse_code=RunPython.noop,
            elidable=True,
        ),
    ]
