# Generated by Django 4.2.4 on 2023-08-31 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=256, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("config", models.JSONField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=512, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FieldType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=256, unique=True)),
                ("config_schema", models.JSONField(blank=True, null=True)),
                ("value_schema", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(blank=True, max_length=512, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScreenField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_required", models.BooleanField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screen_field_schemas",
                        to="shark_task_fields.field",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screen_field_schemas",
                        to="shark_task_fields.screen",
                    ),
                ),
            ],
            options={
                "unique_together": {("screen", "field")},
            },
        ),
        migrations.AddField(
            model_name="screen",
            name="fields",
            field=models.ManyToManyField(
                blank=True, through="shark_task_fields.ScreenField", to="shark_task_fields.field"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="field_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="fields", to="shark_task_fields.fieldtype"
            ),
        ),
    ]
